---
# Tareas que se ejecutan en el rol acr

- name: Asegurarse de que Podman esté instalado
  become: true
  ansible.builtin.apt:
    name: podman
    update_cache: yes
    state: present

- name: Login en el Azure Container Registry (ACR)
  containers.podman.podman_login:
    registry: "{{ acr_login_server }}"
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"

# Descargar imágenes desde Docker Hub (repositorio público)
- name: Descargar imagen de Nginx
  containers.podman.podman_image:
    name: "docker.io/nginx"
    pull: yes

- name: Descargar imagen de Redis
  containers.podman.podman_image:
    name: "mcr.microsoft.com/oss/bitnami/redis"
    tag: "6.0.8"
    pull: yes

- name: Descargar imagen de Azure-vote-front
  containers.podman.podman_image:
    name: "docker.io/fernandezsalazarnieve/azure-vote-front"
    tag: "v1"
    pull: yes

# Etiquetar y hacer push de las imágenes directamente al ACR
- name: Etiquetar y subir la imagen de Nginx a ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/nginx"
    tag: "latest"
    push: yes

- name: Etiquetar y subir la imagen de Redis a ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/redis"
    tag: "6.0.8"
    push: yes

- name: Etiquetar y subir la imagen de Azure-vote-front a ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/azure-vote-front"
    tag: "latest"
    push: yes

