---
- name: Configurar conexión con AKS
  set_fact:
    kube_config: "/home/nefr/.kube/config"

- name: Desplegar Redis en AKS
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config }}"
    state: present
    definition: "{{ lookup('template', 'redis_deployment.yml.j2') }}"

- name: Crear servicio Redis en AKS
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config }}"
    state: present
    definition: "{{ lookup('template', 'redis_service.yml.j2') }}"

- name: Crear PersistentVolumeClaim para Redis
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config }}"
    state: present
    definition: "{{ lookup('template', 'redis_pvc.yml.j2') }}"

- name: Desplegar Azure Vote Front en AKS
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config }}"
    state: present
    definition: "{{ lookup('template', 'azure_vote_front_deployment.yml.j2') }}"

- name: Crear servicio Azure Vote Front en AKS
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config }}"
    state: present
    definition: "{{ lookup('template', 'azure_vote_front_service.yml.j2') }}"
