---
- name: Setup ACR and push images
  hosts: localhost
  vars_files:
    - secrets.yml
  vars:
    acr_name: "nievecp2acr"
    acr_username: "nievecp2acr" 
    acr_login_server: "nievecp2acr.azurecr.io"
  tasks:
    - name: Pull, build, tag and push images to ACR
      include_role:
        name: acr

- name: Setup Webserver
  hosts: vm
  vars_files:
    - secrets.yml
  tasks:
    - name: Configure VM with Podman and deploy web server
      include_role:
        name: vm

- name: Setup AKS
  hosts: localhost
  vars_files:
    - secrets.yml
  vars:
    acr_name: "nievecp2acr.azurecr.io" 
  tasks:
    - name: Deploy app to AKS
      include_role:
        name: aks


